using System;
using UnityEngine;

namespace MahjongOut3D.TileSystem
{
    /// <summary>
    /// Represents a single Mahjong tile instance inside the 3D puzzle block.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class MahjongTile : MonoBehaviour
    {
        [Header("Identity")]
        [SerializeField] private int tileId;
        [SerializeField] private int matchId;
        [SerializeField] private Vector3Int gridCoordinate;

        [Header("Components")]
        [SerializeField] private MeshRenderer meshRenderer;
        [SerializeField] private MeshRenderer matchIndicatorRenderer;
        [SerializeField] private Collider tileCollider;
        [SerializeField] private Animator animator;
        [SerializeField] private TileOutlinePresenter outlinePresenter;
        [SerializeField] private TileVisualController visualController;

        [Header("Runtime")]
        [SerializeField] private TileState state = TileState.Hidden;

        private static readonly int BaseColorId = Shader.PropertyToID("_BaseColor");
        private static readonly int ColorId = Shader.PropertyToID("_Color");

        private MaterialPropertyBlock baseColorPropertyBlock;
        private bool hasDebugBaseColor;
        private Color debugBaseColor = Color.white;

        /// <summary>
        /// Occurs when the tile changes runtime state.
        /// </summary>
        public event Action<TileStateChangedEvent> StateChanged;

        /// <summary>
        /// Occurs when the tile enters or exits the selected state.
        /// </summary>
        public event Action<TileSelectionChangedEvent> SelectionChanged;

        /// <summary>
        /// Gets the unique tile identifier.
        /// </summary>
        public int TileId => tileId;

        /// <summary>
        /// Gets the shared match identifier used to pair this tile.
        /// </summary>
        public int MatchId => matchId;

        /// <summary>
        /// Gets the logical grid coordinate inside the voxel block.
        /// </summary>
        public Vector3Int GridCoordinate => gridCoordinate;

        /// <summary>
        /// Gets the primary tile renderer.
        /// </summary>
        public MeshRenderer MeshRenderer => meshRenderer;

        /// <summary>
        /// Gets the optional renderer used to display a match-indicator material on the tile.
        /// </summary>
        public MeshRenderer MatchIndicatorRenderer => matchIndicatorRenderer;

        /// <summary>
        /// Gets the tile collider used for hit testing.
        /// </summary>
        public Collider TileCollider => tileCollider;

        /// <summary>
        /// Gets the tile animator reference.
        /// </summary>
        public Animator Animator => animator;

        /// <summary>
        /// Gets the tile outline presenter.
        /// </summary>
        public TileOutlinePresenter Outline => outlinePresenter;

        /// <summary>
        /// Gets the tile visual controller.
        /// </summary>
        public TileVisualController VisualController => visualController;

        /// <summary>
        /// Gets the current tile state.
        /// </summary>
        public TileState State => state;

        /// <summary>
        /// Gets a value indicating whether the tile can currently receive pointer hits.
        /// </summary>
        public bool IsInteractable => state == TileState.Visible || state == TileState.Selected;

        /// <summary>
        /// Gets a value indicating whether the tile has already been removed from the puzzle.
        /// </summary>
        public bool IsRemoved => state == TileState.Removed;

        /// <summary>
        /// Gets a value indicating whether the tile is currently in the matched transition state.
        /// </summary>
        public bool IsMatched => state == TileState.Matched;

        /// <summary>
        /// Applies serialized defaults once the component awakens.
        /// </summary>
        private void Awake()
        {
            CacheReferences();
            ApplyStateToPresentation(state, true);
        }

        /// <summary>
        /// Auto-caches tile references in the editor when values change.
        /// </summary>
        private void OnValidate()
        {
            CacheReferences();
        }

        /// <summary>
        /// Applies runtime data generated by a level loader or voxel generator.
        /// </summary>
        /// <param name="runtimeData">Tile runtime data to apply.</param>
        public void ApplyRuntimeData(TileRuntimeData runtimeData)
        {
            if (runtimeData == null)
            {
                return;
            }

            tileId = runtimeData.TileId;
            matchId = runtimeData.MatchId;
            gridCoordinate = runtimeData.GridCoordinate;
            transform.localPosition = runtimeData.LocalPosition;
            transform.localRotation = Quaternion.Euler(runtimeData.LocalEulerAngles);
            gameObject.name = $"MahjongTile_{tileId}_{matchId}";
        }

        /// <summary>
        /// Updates the local-space transform driven by the voxel grid.
        /// </summary>
        /// <param name="localPosition">Local-space position to apply.</param>
        /// <param name="localEulerAngles">Local-space rotation to apply.</param>
        public void SetLocalPose(Vector3 localPosition, Vector3 localEulerAngles)
        {
            transform.localPosition = localPosition;
            transform.localRotation = Quaternion.Euler(localEulerAngles);
        }

        /// <summary>
        /// Changes the tile visibility state.
        /// </summary>
        /// <param name="isVisible">True to show the tile; otherwise false.</param>
        public void SetVisible(bool isVisible)
        {
            SetState(isVisible ? TileState.Visible : TileState.Hidden);
        }

        /// <summary>
        /// Selects the tile when it is currently visible.
        /// </summary>
        /// <returns>True when the tile becomes selected; otherwise false.</returns>
        public bool TrySelect()
        {
            if (state == TileState.Selected)
            {
                return true;
            }

            if (state != TileState.Visible)
            {
                return false;
            }

            SetState(TileState.Selected);
            return true;
        }

        /// <summary>
        /// Returns a selected tile back to the visible state.
        /// </summary>
        public void Deselect()
        {
            if (state == TileState.Selected)
            {
                SetState(TileState.Visible);
            }
        }

        /// <summary>
        /// Marks the tile as matched and disables further interaction.
        /// </summary>
        public void MarkMatched()
        {
            SetState(TileState.Matched);
        }

        /// <summary>
        /// Marks the tile as removed and hides its presentation.
        /// </summary>
        public void MarkRemoved()
        {
            SetState(TileState.Removed);
        }

        /// <summary>
        /// Resets the tile to a hidden default state.
        /// </summary>
        public void ResetTile()
        {
            SetState(TileState.Hidden, true);
        }

        /// <summary>
        /// Restores a removed or matched tile back into the active puzzle.
        /// </summary>
        /// <param name="isVisible">True to restore the tile as visible; otherwise hidden.</param>
        public void Restore(bool isVisible)
        {
            SetState(isVisible ? TileState.Visible : TileState.Hidden, true);
        }

        /// <summary>
        /// Updates the logical grid coordinate used by the level systems.
        /// </summary>
        /// <param name="coordinate">New grid coordinate.</param>
        public void SetGridCoordinate(Vector3Int coordinate)
        {
            gridCoordinate = coordinate;
        }

        /// <summary>
        /// Applies a runtime base color override used to visually distinguish matched pairs.
        /// </summary>
        /// <param name="color">Base color for this tile instance.</param>
        public void SetDebugMatchColor(Color color)
        {
            if (visualController == null)
            {
                CacheReferences();
            }

            hasDebugBaseColor = true;
            debugBaseColor = color;
            visualController?.SetRuntimeBaseColor(color);
            visualController?.ApplyState(state, true);
            ApplyDirectBaseColorOverride();
        }

        /// <summary>
        /// Assigns a material to the optional match-indicator renderer used for gameplay testing.
        /// </summary>
        /// <param name="material">Material to display on the indicator quad, or null to leave the current material unchanged.</param>
        public void SetMatchIndicatorMaterial(Material material)
        {
            if (matchIndicatorRenderer == null)
            {
                CacheReferences();
            }

            if (matchIndicatorRenderer != null && material != null)
            {
                matchIndicatorRenderer.sharedMaterial = material;
            }
        }

        /// <summary>
        /// Changes the runtime tile state and updates visuals and colliders.
        /// </summary>
        /// <param name="newState">New tile state.</param>
        /// <param name="force">True to force the transition even if the state matches.</param>
        public void SetState(TileState newState, bool force = false)
        {
            if (!force && state == newState)
            {
                return;
            }

            TileState previousState = state;
            state = newState;
            ApplyStateToPresentation(state, false);

            TileStateChangedEvent stateEvent = new TileStateChangedEvent(this, previousState, state);
            StateChanged?.Invoke(stateEvent);

            bool wasSelected = previousState == TileState.Selected;
            bool isSelected = state == TileState.Selected;
            if (wasSelected != isSelected)
            {
                SelectionChanged?.Invoke(new TileSelectionChangedEvent(this, isSelected));
            }
        }

        /// <summary>
        /// Caches missing component references from the tile hierarchy.
        /// </summary>
        private void CacheReferences()
        {
            if (visualController == null)
            {
                visualController = GetComponentInChildren<TileVisualController>(true);
            }

            if (meshRenderer == null)
            {
                meshRenderer = visualController != null ? visualController.GetPrimaryRenderer() : GetComponentInChildren<MeshRenderer>(true);
            }

            if (matchIndicatorRenderer == null)
            {
                MeshRenderer[] renderers = GetComponentsInChildren<MeshRenderer>(true);
                for (int index = 0; index < renderers.Length; index++)
                {
                    MeshRenderer renderer = renderers[index];
                    if (renderer != null && renderer != meshRenderer && renderer.gameObject.name.Equals("Quad", StringComparison.OrdinalIgnoreCase))
                    {
                        matchIndicatorRenderer = renderer;
                        break;
                    }
                }
            }

            if (tileCollider == null)
            {
                tileCollider = GetComponentInChildren<Collider>(true);
            }

            if (animator == null)
            {
                animator = GetComponentInChildren<Animator>(true);
            }

            if (outlinePresenter == null)
            {
                outlinePresenter = visualController != null ? visualController.GetOutlinePresenter() : GetComponentInChildren<TileOutlinePresenter>(true);
            }
        }

        /// <summary>
        /// Applies runtime state to colliders and visual presentation.
        /// </summary>
        /// <param name="currentState">Tile state to present.</param>
        /// <param name="instant">True to snap visual transitions immediately.</param>
        private void ApplyStateToPresentation(TileState currentState, bool instant)
        {
            if (tileCollider != null)
            {
                tileCollider.enabled = currentState == TileState.Visible || currentState == TileState.Selected;
            }

            if (matchIndicatorRenderer != null)
            {
                matchIndicatorRenderer.enabled = currentState != TileState.Hidden && currentState != TileState.Removed;
            }

            if (visualController != null)
            {
                visualController.ApplyState(currentState, instant);
            }
        }

        /// <summary>
        /// Reapplies the runtime base color directly onto the primary renderer so debug tinting stays visible.
        /// </summary>
        private void ApplyDirectBaseColorOverride()
        {
            if (!hasDebugBaseColor)
            {
                return;
            }

            if (meshRenderer == null)
            {
                CacheReferences();
            }

            if (meshRenderer == null)
            {
                return;
            }

            Material sharedMaterial = meshRenderer.sharedMaterial;
            if (sharedMaterial == null)
            {
                return;
            }

            if (baseColorPropertyBlock == null)
            {
                baseColorPropertyBlock = new MaterialPropertyBlock();
            }

            meshRenderer.GetPropertyBlock(baseColorPropertyBlock);

            bool applied = false;
            if (sharedMaterial.HasProperty(BaseColorId))
            {
                baseColorPropertyBlock.SetColor(BaseColorId, debugBaseColor);
                applied = true;
            }

            if (sharedMaterial.HasProperty(ColorId))
            {
                baseColorPropertyBlock.SetColor(ColorId, debugBaseColor);
                applied = true;
            }

            if (applied)
            {
                meshRenderer.SetPropertyBlock(baseColorPropertyBlock);
            }
        }
    }
}
